branch-defaults:
  default:
    environment: spring-mvc-docker-env1
    group_suffix: null
global:
  application_name: spring-mvc-docker
  branch: null
  default_ec2_keyname: null
  default_platform: docker
  default_region: us-west-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  repository: null
  sc: null
  workspace_type: Application
