branch-defaults:
  default:
    environment: TestApp-env
  master:
    environment: spring-mvc-docker-env1
    group_suffix: null
deploy:
  artifact: target/mvc-0.0.1-SNAPSHOT.jar
environment-defaults:
  TestApp-env:
    branch: null
    repository: null
  TestApp-env-2:
    branch: master
    repository: origin
global:
  application_name: spring-mvc-docker
  branch: null
  default_ec2_keyname: null
  default_platform: docker
  default_region: us-west-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  repository: null
  sc: git
  workspace_type: Application
